config/routes.rb
Rails.application.routes.draw do
  get 'home',     to: 'home#index'
  get 'pricing',  to: 'home#pricing'
  get 'about-us', to: 'home#about_us'
  get 'hello',    to: 'home#hello'
  get 'sitemap',  to: 'sitemap#index', constraints: { format: 'xml' }

  get '/404', to: 'errors#not_found'
  get '/422', to: 'errors#unacceptable'
  get '/500', to: 'errors#internal_error'

  mount ActionCable.server, at: '/cable'

  devise_for :users, path: 'account', controllers: {
    registrations: 'users/registrations', sessions: 'users/track_sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :contacts, only: %i[new create]

  namespace :account do
    root 'dashboard#index'
    resources :companies do
      resources :pages, except: %i[edit update] do
        patch :rate, on: :member
      end
      resources :videos, only: %i[index]
      get :download, on: :member
      collection do
        resource :chrome_extensions, only: %i[new create]
      end
    end
    resources :comments,      only: %i[create destroy]
    resources :tenants,       only: %i[show index]
    resource  :my_tenant,     only: %i[show edit update]
    resources :analytics,     only: %i[index]
    resources :contacts,      only: %i[index destroy]
    resources :notifications, only: [] do
      member do
        get 'read', to: 'notifications#read', as: :read
      end
      collection do
        get 'read_all', to: 'notifications#read_all', as: :read_all
      end
    end
    resource :profile, only: %i[show edit update], controller: 'profile' do
      resource :tokens, only: %i[create destroy]
    end
    resources :users do
      member do
        post :impersonate
      end
      collection do
        post :stop_impersonating
        get  :download
      end
    end
    get 'chart-for-users-by-week',     to: 'charts#registered_users'
    get 'chart-for-companies-by-week', to: 'charts#created_companies'
    get 'chart-for-users-by-month',    to: 'charts#registered_users_summary'
    get 'chart-for-users-logins',      to: 'charts#users_logins'
  end

  authenticated :user do
    root 'account/dashboard#index', as: :authenticated_root
  end

  root 'home#index'

  namespace :api, defaults: { format: :json } do
    as :user do
      resources :companies, only: :index
    end
  end
end

app/views/layouts/shared/_google_analytics.html.erb
<% if Rails.env == "production" %>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-112609815-1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-112609815-1');
  </script>
<% end %>

app/views/layouts/shared/_notifications.html.slim
li.dropdown.dropdown-notification.nav-item
  a.nav-link.nav-link-label data-toggle="dropdown" href="#"
    i.ficon.ft-bell
    span#notifications-count.badge.badge-pill.badge-default.badge-danger.badge-default.badge-up
      = "#{notifications.count}"
  ul.dropdown-menu.dropdown-menu-media.dropdown-menu-right
    li.dropdown-menu-header
      h6.dropdown-header.m-0
        span.grey.darken-2 Notifications
    li.scrollable-container.media-list.without-notifications class=(notifications.empty? ? '' : 'hidden')
      .dropdown-item.text-muted.text-center Nothing to show
    li.scrollable-container.media-list.with-notifications class=(notifications.empty? ? 'hidden' : '')
      - notifications.each do |notification|
        = link_to read_account_notification_path(notification.id),
                class: "media",
                id: "#{dom_id(notification)}",
                remote: true do
          .media-left.align-self-center
            i class=(notification.status == 'error'? 'ft-alert-triangle icon-bg-circle bg-yellow bg-darken-3' : 'ft-check-circle icon-bg-circle bg-cyan')
          .media-body
            h6.media-heading class=(notification.status == 'error'? 'yellow darken-3' : '') = notification.content
            small
              time.media-meta.text-muted
                = timeago_tag notification.created_at
    li.dropdown-menu-footer class=(notifications.empty? ? 'hidden' : '')
      = link_to 'Read all notifications', read_all_account_notifications_path, class: "dropdown-item text-muted text-center", remote: true
        / a.dropdown-item.text-muted.text-center href="#"  Read all notifications

app/views/layouts/shared/_user_menu.html.slim
ul.nav.navbar-nav.float-right
  li.dropdown.dropdown-user.nav-item
    = link_to account_profile_path, { class: 'dropdown-toggle nav-link dropdown-user-link' } do
      span.avatar.avatar-online
        = image_tag(current_user.avatar)
        i
      span.user-name
        = current_user.full_name
    .dropdown-menu.dropdown-menu-right
      = link_to edit_account_profile_path, class: "dropdown-item" do
        i.fa
        | Edit Profile
      - if impersonated?
        .dropdown-divider
        = link_to stop_impersonating_account_users_path, method: :post, class: "dropdown-item" do
          i.fa.fa-arrow-left
          | Back to admin
      .dropdown-divider
      = link_to destroy_user_session_path, method: :delete, class: "dropdown-item" do
        i.fa.fa-sign-out
        | Log out