config/routes.rb
Rails.application.routes.draw do
  get 'home',     to: 'home#index'
  get 'pricing',  to: 'home#pricing'
  get 'about-us', to: 'home#about_us'
  get 'hello',    to: 'home#hello'
  get 'sitemap',  to: 'sitemap#index', constraints: { format: 'xml' }

  get '/404', to: 'errors#not_found'
  get '/422', to: 'errors#unacceptable'
  get '/500', to: 'errors#internal_error'

  mount ActionCable.server, at: '/cable'

  devise_for :users, path: 'account', controllers: {
    registrations: 'users/registrations', sessions: 'users/track_sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :contacts, only: %i[new create]

  namespace :account do
    root 'dashboard#index'
    resources :companies do
      resources :pages, except: %i[edit update] do
        patch :rate, on: :member
      end
      resources :videos, only: %i[index]
      get :download, on: :member
      collection do
        resource :chrome_extensions, only: %i[new create]
      end
    end
    resources :comments,      only: %i[create destroy]
    resources :tenants,       only: %i[show index]
    resource  :my_tenant,     only: %i[show edit update]
    resources :analytics,     only: %i[index]
    resources :contacts,      only: %i[index destroy]
    resources :notifications, only: [] do
      member do
        get 'read', to: 'notifications#read', as: :read
      end
      collection do
        get 'read_all', to: 'notifications#read_all', as: :read_all
      end
    end
    resource :profile, only: %i[show edit update], controller: 'profile' do
      resource :tokens, only: %i[create destroy]
    end
    resources :users do
      member do
        post :impersonate
      end
      collection do
        post :stop_impersonating
        get  :download
      end
    end
    get 'chart-for-users-by-week',     to: 'charts#registered_users'
    get 'chart-for-companies-by-week', to: 'charts#created_companies'
    get 'chart-for-users-by-month',    to: 'charts#registered_users_summary'
    get 'chart-for-users-logins',      to: 'charts#users_logins'
  end

  authenticated :user do
    root 'account/dashboard#index', as: :authenticated_root
  end

  root 'home#index'

  namespace :api, defaults: { format: :json } do
    as :user do
      resources :companies, only: :index
    end
  end
end

app/views/layouts/shared/header/_header_landing.html.slim
.header-navbar.navbar-expand-sm.navbar.navbar-horizontal.navbar-light.navbar-shadow.border-grey.border-lighten-2.navbar-brand-center.space-between.land-font.fixed-top.pl-5 data-nav="brand-center"
  /! Horizontal menu content
  .horizontal-menu.navbar-container.ml-5
    = link_to root_path do
      = image_tag("logo1.png", alt: 'Sales Assistant', id: 'logo')
  .horizontal-menu.navbar-container.ml-0
    ul.nav.navbar-nav.text-uppercase data-menu="menu-navigation"
      li.nav-item
        = link_to "home", home_path, class:"nav-link font-medium-2"
      li.nav-item
        = link_to "about us", about_us_path, class:"nav-link font-medium-2"
      li.nav-item
        = link_to "pricing", pricing_path, class:"nav-link font-medium-2"
      li.nav-item
        = link_to "contact us", new_contact_path, class:"nav-link font-medium-2"
  - if user_signed_in?
    .horizontal-menu.navbar-container
      = render 'layouts/shared/user_menu'
  - else
    .horizontal-menu.navbar-container.ml-0.pt-2
      .nav.navbar-nav data-menu="menu-navigation"
        = link_to "sign in", new_session_path(resource_name), class: "nav-link font-medium-2 text-uppercase"
        p.nav-item.pt-2.font-medium-2
          | or
        .nav-item.text-uppercase
          = link_to "sign up", new_user_registration_path, class: "nav-link font-medium-2"
  /! /horizontal menu content