config/routes.rb
Rails.application.routes.draw do
  get 'home',     to: 'home#index'
  get 'pricing',  to: 'home#pricing'
  get 'about-us', to: 'home#about_us'
  get 'hello',    to: 'home#hello'
  get 'sitemap',  to: 'sitemap#index', constraints: { format: 'xml' }

  get '/404', to: 'errors#not_found'
  get '/422', to: 'errors#unacceptable'
  get '/500', to: 'errors#internal_error'

  mount ActionCable.server, at: '/cable'

  devise_for :users, path: 'account', controllers: {
    registrations: 'users/registrations', sessions: 'users/track_sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :contacts, only: %i[new create]

  namespace :account do
    root 'dashboard#index'
    resources :companies do
      resources :pages, except: %i[edit update] do
        patch :rate, on: :member
      end
      resources :videos, only: %i[index]
      get :download, on: :member
      collection do
        resource :chrome_extensions, only: %i[new create]
      end
    end
    resources :comments,      only: %i[create destroy]
    resources :tenants,       only: %i[show index]
    resource  :my_tenant,     only: %i[show edit update]
    resources :analytics,     only: %i[index]
    resources :contacts,      only: %i[index destroy]
    resources :notifications, only: [] do
      member do
        get 'read', to: 'notifications#read', as: :read
      end
      collection do
        get 'read_all', to: 'notifications#read_all', as: :read_all
      end
    end
    resource :profile, only: %i[show edit update], controller: 'profile' do
      resource :tokens, only: %i[create destroy]
    end
    resources :users do
      member do
        post :impersonate
      end
      collection do
        post :stop_impersonating
        get  :download
      end
    end
    get 'chart-for-users-by-week',     to: 'charts#registered_users'
    get 'chart-for-companies-by-week', to: 'charts#created_companies'
    get 'chart-for-users-by-month',    to: 'charts#registered_users_summary'
    get 'chart-for-users-logins',      to: 'charts#users_logins'
  end

  authenticated :user do
    root 'account/dashboard#index', as: :authenticated_root
  end

  root 'home#index'

  namespace :api, defaults: { format: :json } do
    as :user do
      resources :companies, only: :index
    end
  end
end

app/views/layouts/_footer.html.slim
footer.footer.footer-light.navbar-shadow.py-5.ftr-height
  .app-content.container.center-layout
    .row
      .col-md-6
        .row
          .foot-logo
            = image_tag("logo1.png", alt: 'Sales Assistant', id: 'logo')
        .margins-copyright
          .row
            span.float-md-right.d-block.d-md-inline-blockd-none.d-lg-block
              | Hand-crafted & Made with
              i.fe.fe-heart.pink
          .row
            span.float-md-left.d-block.d-md-inline-block
              | Copyright ©
              = Date.today.year
              a.text-bold-800.grey.darken-2[href="https://github.com/Ruby-IF081/heroes_team_app" target="_blank"]
                |  Heroes Team
              | , All rights reserved.
      .col-md-6
        .row
          .col-sm-4.text-left
            h6.margin-head-footer.text-uppercase company
            = link_to "Home", home_path, class: "nav-link"
            = link_to "About Us", about_us_path, class: "nav-link"
            = link_to "Contact Us", new_contact_path, class: "nav-link"
            = link_to "Lorem Ipsum", '#', class: "nav-link"
          .col-sm-4.text-left
            h6.margin-head-footer.text-uppercase support
            = link_to "Help & Support", "#", class: "nav-link"
            = link_to "Pricing", pricing_path, class: "nav-link"
          .col-sm-4.text-left
            h6.margin-head-footer.text-uppercase social media
            = link_to "GitHub", 'https://github.com/Ruby-IF081', class: "nav-link"

app/views/layouts/_header.html.slim
nav.header-navbar.navbar-expand-md.navbar.navbar-with-menu.navbar-static-top.navbar-dark.bg-gradient-x-grey-blue.navbar-brand-center
  .navbar-wrapper
    .navbar-container.container
      #navbar-mobile.collapse.navbar-collapse.container.center-layout
        ul.nav.navbar-nav.mr-auto.float-left
          = link_to root_path do
            = image_tag("logo2.png", alt: 'Sales Assistant', id: 'logo1')
        - if user_signed_in?
          ul.nav.navbar-nav.float-right
            = render 'layouts/shared/notifications'
            = render 'layouts/shared/user_menu'

app/views/layouts/_nav.html.slim
#sticky-wrapper.sticky-wrapper
  .header-navbar.navbar-expand-sm.navbar.navbar-horizontal.navbar-fixed.navbar-light.navbar-without-dd-arrow.navbar-shadow.menu-border.navbar-brand-center[role="navigation" data-menu="menu-wrapper" data-nav="brand-center" style=""]
    .navbar-container.main-menu-content.container[data-menu="menu-container"]
      ul#main-menu-navigation.nav.navbar-nav[data-menu="menu-navigation"]
        li.dropdown.nav-item.active[data-menu="dropdown"]
          = link_to 'Dashboard', account_root_path, class:'dropdown-toggle nav-link'
        - if current_user.privileged?
          li.dropdown.nav-item[data-menu="dropdown"]
            a.dropdown-toggle.nav-link[href="#" data-toggle="dropdown"]
              span
                | Users
            ul.dropdown-menu
              li.dropdown[data-menu="dropdown-submenu"]
                = link_to 'User list', account_users_path, class:'dropdown-item'
              li.dropdown[data-menu="dropdown-submenu"]
                = link_to 'Add new user', new_account_user_path, class:'dropdown-item'
        li.dropdown.nav-item[data-menu="dropdown"]
          = link_to 'Companies', account_companies_path, class:'dropdown-toggle nav-link'
        - if current_user.admin?
          li.dropdown.nav-item[data-menu="dropdown"]
            = link_to 'My Tenant', account_my_tenant_path, class:'dropdown-toggle nav-link'
          li.dropdown.nav-item[data-menu="dropdown"]
            = link_to 'Analytics', account_analytics_path, class:'dropdown-toggle nav-link'
        - if current_user.super_admin?
          li.dropdown.nav-item[data-menu="dropdown"]
            = link_to 'Contacts', account_contacts_path, class: 'dropdown-toggle nav-link'

app/views/layouts/account.html.slim
doctype html
html
  head
    = display_meta_tags(default_meta_tags)
    = favicon_link_tag 'favicon.ico'
    = csrf_meta_tags
    = stylesheet_link_tag    'account/application', media: 'all'
    = stylesheet_link_tag    'https://fonts.googleapis.com/css?family=Montserrat'
    = javascript_include_tag 'account/application'
    = render_google_analytics
  body data-open="hover" data-menu="horizontal-menu" data-col="2-columns" class="horizontal-layout horizontal-menu 2-columns   menu-expanded"
    = render 'account/shared/header'
    = render 'account/shared/nav'
    .content
      = yield
    = render 'layouts/footer'
    = any_login_here if defined?(AnyLogin)

app/views/layouts/application.html.slim
doctype html
html
  head
    = display_meta_tags(default_meta_tags)
    = favicon_link_tag 'favicon.ico'
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = render_google_analytics
  body data-open="hover"
    = render 'layouts/header'
    = render 'layouts/nav' if user_signed_in?
    .content
      .app-content.container.center-layout
        .row.alert
          - flash.each do |message_type, message|
            = content_tag(:div, message, class: "alert alert-#{message_type}")
        = yield
    = any_login_here if defined?(AnyLogin)
    = render 'layouts/footer'

app/views/layouts/application.pdf.slim
doctype html
html
  head
    title Generated PDF
    = wicked_pdf_stylesheet_link_tag 'application'
  body
    .app-content.container.center-layout.mt-2.mb-5
      = yield

app/views/layouts/errors.html.slim
doctype html
html
  head
    = display_meta_tags(default_meta_tags)
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet"
  body.blank-page
    .app-content.container.center-layout.mt-2.mb-5
      .content-wrapper
        .content-body
          section.flexbox-container
            .col-12.d-flex.justify-content-center
              .col-md-4.p-0
                = yield
                .error-footer.card-footer.bg-transparent
                  .row
                    p.text-muted.text-center.col-12.py-1
                      | Copyright ©&nbsp;
                      = Date.today.year
                      | &nbsp;
                      = link_to 'Heroes Team', "https://github.com/Ruby-IF081/heroes_team_app", target: "_blank"
                      | .&nbsp;All rights reserved.
    = any_login_here if defined?(AnyLogin)

app/views/layouts/landing.html.slim
doctype html
html
  head
    = display_meta_tags(default_meta_tags)
    = favicon_link_tag 'favicon.ico'
    = csrf_meta_tags
    = stylesheet_link_tag    'landing/application', media: 'all'
    = javascript_include_tag 'application'
    = render_google_analytics
    link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet"
  body.land-font
    = render 'layouts/shared/header/header_landing'
    .content
      = yield
    = any_login_here if defined?(AnyLogin)
    = render 'layouts/footer'